import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Navbar from '../components/Navbar';
import Jumbotron from '../components/Jumbotron';
import Carousel from '../components/Carousel';
import Links from '../components/Links';
import Contributors from '../components/Contributors';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sapling</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/sapling-logo.png" />
      </Head>
      <Navbar />
      <main className="container w-75">
        <Jumbotron />
        <Carousel />
        <Links />
        <Contributors />
      </main>
    </div>
  )
}
