import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Navbar from '../components/Navbar';
import Jumbotron from '../components/Jumbotron';
import Carousel from '../components/Carousel';
import Links from '../components/Links';
import Contributors from '../components/Contributors';
import nextLogo from '../public/Nextjs-logo.svg';
import osLabsLogo from '../public/oslabs-icon.png';
import bootstrapLogo from '../public/Bootstrap_logo.svg';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sapling</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/sapling-logo.png" />
      </Head>
      <Navbar />
      <main className="container">
        <Jumbotron />
        <Carousel />
        <Links />
        <Contributors />
      </main>
      <footer className="d-flex justify-content-around">
        <div className="d-flex flex-column align-items-center">
          <span>developed under</span>
          <a href="https://opensourcelabs.io/" target="_blank" rel="noreferrer">
           <Image src={osLabsLogo} alt="OSLabs Logo"/>
          </a>
        </div>
      </footer>
    </div>
  )
}
