import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sapling</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/sapling-logo.png" />
      </Head>
      <Navbar />
      <main className="container">
      </main>
      <footer className="d-flex justify-content-around">
        <div className="d-flex flex-column align-items-center">
          <span>developed under</span>
          <a href="https://opensourcelabs.io/" target="_blank" rel="noreferrer">
           <Image src={osLabsLogo} alt="OSLabs Logo"/>
          </a>
        </div>
      </footer>
    </div>
  )
}